#!/bin/bash
# This script installs the library in the current shell or in the init file

# find init file using current shell
if [[ -n "$BASH" ]]; then
    INIT_FILE="$HOME/.bashrc"
elif [[ -n "$ZSH_VERSION" ]]; then
    INIT_FILE="$HOME/.zshrc"
else
    echo "This shell is not supported" 1>&2
    exit 1
fi

cd $(dirname $0)
CURRENT_DIR="$(pwd)"
cd "$OLDPWD"
BIN_PATH="$CURRENT_DIR/bin"
SRC_PATH="$CURRENT_DIR/src"

set -e

if [[ -n "$1" ]]; then
    if [[ -e "$1" ]]; then
        INIT_FILE="$1"
    else
        echo "file named '$1' does not exist" 1>&2
        exit 1
    fi
fi

if echo "$PATH" | grep -q "$BIN_PATH"; then
    if [[ "$(which mkfile)" != "$BIN_PATH/mkfile" ]] && [[ "$(which gcc+)" != "$BIN_PATH/gcc+" ]]; then
        echo "WARNING: multiple versions of the library found." 1>&2
        exit 1
    else
        echo "This library is already available in your current shell"
    fi
else
    # compile whatchar.c
    $BIN_PATH/gcc+ $SRC_PATH/whatchar.c
    echo "export PATH=\"\$PATH:$BIN_PATH\"" >> "$INIT_FILE"
    export PATH="$PATH:$BIN_PATH"
    echo "This library has been permanently installed"
fi
